#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                  (HAL_CLK_HFCLK_SOURCE_HFXO)
#define HAL_CLK_LFECLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFBCLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_LFXO_PRESENT                  (1)
#define BSP_CLK_HFXO_PRESENT                  (1)
#define BSP_CLK_LFXO_INIT                      CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                    (32U)
#define BSP_CLK_LFXO_FREQ                     (32768U)
#define HAL_CLK_LFACLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_HFXO_FREQ                     (38400000UL)
#define BSP_CLK_HFXO_CTUNE                    (338)
#define BSP_CLK_HFXO_INIT                      CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_CTUNE_TOKEN              (0)
#define HAL_CLK_HFXO_AUTOSTART                (HAL_CLK_HFXO_AUTOSTART_NONE)
// [CMU]$

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[CSEN0]
// [CSEN0]$

// $[DCDC]
#define BSP_DCDC_PRESENT                 (1)

#define HAL_DCDC_BYPASS                  (0)
#define BSP_DCDC_INIT    \
{ \
emuPowerConfig_DcdcToDvdd, /* DCDC to DVDD */ \
emuDcdcMode_LowNoise, /* Low-noise mode in EM0 */ \
1800, /* Nominal output voltage for DVDD mode, 1.8V */ \
15, /* Nominal EM0/1 load current of less than 15mA */ \
10, /* Nominal EM2/3/4 load current less than 10uA */ \
200, /* Maximum average current of 200mA
(assume strong battery or other power source) */ \
emuDcdcAnaPeripheralPower_DCDC,/* Select DCDC as analog power supply (lower power) */ \
160, /* Maximum reverse current of 160mA */ \
emuDcdcLnCompCtrl_4u7F, /* 4.7uF DCDC capacitor */ \
}
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[GPIO]

#define PORTIO_GPIO_LED0_PIN       (11U)
#define PORTIO_GPIO_LED0_PORT      (gpioPortC)
#define PORTIO_GPIO_LED1_PIN       (12U)
#define PORTIO_GPIO_LED1_PORT      (gpioPortD)
#define PORTIO_GPIO_LED2_PIN       (14U)
#define PORTIO_GPIO_LED2_PORT      (gpioPortD)
#define PORTIO_GPIO_LED3_PIN       (6U)
#define PORTIO_GPIO_LED3_PORT      (gpioPortF)

#define PORTIO_GPIO_BTN0_PIN        (10U)
#define PORTIO_GPIO_BTN0_PORT       (gpioPortD)

#define PORTIO_GPIO_AT86RST_PIN     (6U)
#define PORTIO_GPIO_AT86RST_PORT    (gpioPortF)
#define PORTIO_GPIO_AT86RST2_PIN     (7U)
#define PORTIO_GPIO_AT86RST2_PORT    (gpioPortF)
// [GPIO]$

// $[I2C0]

// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[LNA]
// [LNA]$

// $[PA]
#define HAL_PA_ENABLE                         (1)

#define HAL_PA_RAMP                           (10UL)
#define HAL_PA_2P4_LOWPOWER                   (0)
#define HAL_PA_POWER                          (252U)
#define BSP_PA_VOLTAGE                        (1800U)
#define HAL_PA_CURVE_HEADER                    "pa_curves_efr32.h"
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PCNT1]
// [PCNT1]$

// $[PCNT2]
// [PCNT2]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]

// [PRS]$

// $[PTI]
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
#define HAL_SERIAL_USART0_ENABLE              (0)
#define HAL_SERIAL_LEUART0_ENABLE             (0)
#define HAL_SERIAL_USART1_ENABLE              (0)
#define HAL_SERIAL_USART2_ENABLE              (0)
#define HAL_SERIAL_RXWAKE_ENABLE              (0)
#define HAL_SERIAL_IDLE_WAKE_ENABLE           (1)

#ifdef BSP_SERIAL_APP_CTS_PIN
#undef BSP_SERIAL_APP_CTS_PIN
#endif
#define BSP_SERIAL_APP_CTS_PIN                (11U)

#ifdef BSP_SERIAL_APP_CTS_PORT
#undef BSP_SERIAL_APP_CTS_PORT
#endif
#define BSP_SERIAL_APP_CTS_PORT               (gpioPortA)

#ifdef BSP_SERIAL_APP_CTS_LOC
#undef BSP_SERIAL_APP_CTS_LOC
#endif
#define BSP_SERIAL_APP_CTS_LOC                (15U)


#ifdef BSP_SERIAL_APP_RTS_PIN
#undef BSP_SERIAL_APP_RTS_PIN
#endif
#define BSP_SERIAL_APP_RTS_PIN                (13U)

#ifdef BSP_SERIAL_APP_RTS_PORT
#undef BSP_SERIAL_APP_RTS_PORT
#endif
#define BSP_SERIAL_APP_RTS_PORT               (gpioPortA)

#ifdef BSP_SERIAL_APP_RTS_LOC
#undef BSP_SERIAL_APP_RTS_LOC
#endif
#define BSP_SERIAL_APP_RTS_LOC                (16U)


#ifdef BSP_SERIAL_APP_RX_PIN
#undef BSP_SERIAL_APP_RX_PIN
#endif
#define BSP_SERIAL_APP_RX_PIN                 (4U)

#ifdef BSP_SERIAL_APP_RX_PORT
#undef BSP_SERIAL_APP_RX_PORT
#endif
#define BSP_SERIAL_APP_RX_PORT                (gpioPortF)

#ifdef BSP_SERIAL_APP_RX_LOC
#undef BSP_SERIAL_APP_RX_LOC
#endif
#define BSP_SERIAL_APP_RX_LOC                 (16U)


#ifdef BSP_SERIAL_APP_TX_PIN
#undef BSP_SERIAL_APP_TX_PIN
#endif
#define BSP_SERIAL_APP_TX_PIN                 (5U)

#ifdef BSP_SERIAL_APP_TX_PORT
#undef BSP_SERIAL_APP_TX_PORT
#endif
#define BSP_SERIAL_APP_TX_PORT                (gpioPortF)

#ifdef BSP_SERIAL_APP_TX_LOC
#undef BSP_SERIAL_APP_TX_LOC
#endif
#define BSP_SERIAL_APP_TX_LOC                 (18U)

#define HAL_SERIAL_APP_RX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_APP_BAUD_RATE              (115200UL)
#define HAL_SERIAL_APP_RXSTOP                 (16UL)
#define HAL_SERIAL_APP_RXSTART                (16UL)
#define HAL_SERIAL_APP_TX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_APP_FLOW_CONTROL           (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_CLK_PIN           (10U)
#define PORTIO_USART0_CLK_PORT          (gpioPortC)
#define PORTIO_USART0_CLK_LOC           (13U)

#define PORTIO_USART0_CS_PIN            (7U)
#define PORTIO_USART0_CS_PORT           (gpioPortC)
#define PORTIO_USART0_CS_LOC            (9U)

#define PORTIO_USART0_RX_PIN            (9U)
#define PORTIO_USART0_RX_PORT           (gpioPortC)
#define PORTIO_USART0_RX_LOC            (13U)

#define PORTIO_USART0_TX_PIN            (8U)
#define PORTIO_USART0_TX_PORT           (gpioPortC)
#define PORTIO_USART0_TX_LOC            (13U)

#define HAL_USART0_ENABLE               (1)

#define BSP_USART0_CS_PIN               (7U)
#define BSP_USART0_CS_PORT              (gpioPortC)
#define BSP_USART0_CS_LOC               (9U)

#define BSP_USART0_CLK_PIN              (10U)
#define BSP_USART0_CLK_PORT             (gpioPortC)
#define BSP_USART0_CLK_LOC              (13U)

#define BSP_USART0_MISO_PIN             (9U)
#define BSP_USART0_MISO_PORT            (gpioPortC)
#define BSP_USART0_MISO_LOC             (13U)

#define BSP_USART0_MOSI_PIN             (8U)
#define BSP_USART0_MOSI_PORT            (gpioPortC)
#define BSP_USART0_MOSI_LOC             (13U)

#define HAL_USART0_FREQUENCY            (1000000UL)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_CLK_PIN           (3U)
#define PORTIO_USART1_CLK_PORT          (gpioPortA)
#define PORTIO_USART1_CLK_LOC           (1U)

#define PORTIO_USART1_CS_PIN            (11U)
#define PORTIO_USART1_CS_PORT           (gpioPortB)
#define PORTIO_USART1_CS_LOC            (3U)

#define PORTIO_USART1_RX_PIN            (4U)
#define PORTIO_USART1_RX_PORT           (gpioPortA)
#define PORTIO_USART1_RX_LOC            (3U)

#define PORTIO_USART1_TX_PIN            (2U)
#define PORTIO_USART1_TX_PORT           (gpioPortA)
#define PORTIO_USART1_TX_LOC            (2U)

#define HAL_USART1_ENABLE               (1)

#define BSP_USART1_CS_PIN               (11U)
#define BSP_USART1_CS_PORT              (gpioPortB)
#define BSP_USART1_CS_LOC               (3U)

#define BSP_USART1_CLK_PIN              (3U)
#define BSP_USART1_CLK_PORT             (gpioPortA)
#define BSP_USART1_CLK_LOC              (1U)

#define BSP_USART1_MISO_PIN             (4U)
#define BSP_USART1_MISO_PORT            (gpioPortA)
#define BSP_USART1_MISO_LOC             (3U)

#define BSP_USART1_MOSI_PIN             (2U)
#define BSP_USART1_MOSI_PORT            (gpioPortA)
#define BSP_USART1_MOSI_LOC             (2U)

#define HAL_USART1_FREQUENCY            (1000000UL)
// [USART1]$

// $[USART2]
#define PORTIO_USART2_CTS_PIN                 (11U)
#define PORTIO_USART2_CTS_PORT                (gpioPortA)
#define PORTIO_USART2_CTS_LOC                 (15U)

#define PORTIO_USART2_RTS_PIN                 (13U)
#define PORTIO_USART2_RTS_PORT                (gpioPortA)
#define PORTIO_USART2_RTS_LOC                 (16U)

#define PORTIO_USART2_RX_PIN                  (4U)
#define PORTIO_USART2_RX_PORT                 (gpioPortF)
#define PORTIO_USART2_RX_LOC                  (16U)

#define PORTIO_USART2_TX_PIN                  (5U)
#define PORTIO_USART2_TX_PORT                 (gpioPortF)
#define PORTIO_USART2_TX_LOC                  (18U)

#define HAL_USART2_ENABLE                     (1)

#define BSP_USART2_CTS_PIN                    (11U)
#define BSP_USART2_CTS_PORT                   (gpioPortA)
#define BSP_USART2_CTS_LOC                    (15U)

#define BSP_USART2_RTS_PIN                    (13U)
#define BSP_USART2_RTS_PORT                   (gpioPortA)
#define BSP_USART2_RTS_LOC                    (16U)

#define BSP_USART2_RX_PIN                     (4U)
#define BSP_USART2_RX_PORT                    (gpioPortF)
#define BSP_USART2_RX_LOC                     (16U)

#define BSP_USART2_TX_PIN                     (5U)
#define BSP_USART2_TX_PORT                    (gpioPortF)
#define BSP_USART2_TX_LOC                     (18U)

#define HAL_USART2_RX_QUEUE_SIZE              (128UL)
#define HAL_USART2_BAUD_RATE                  (115200UL)
#define HAL_USART2_RXSTOP                     (16UL)
#define HAL_USART2_RXSTART                    (16UL)
#define HAL_USART2_TX_QUEUE_SIZE              (128UL)
#define HAL_USART2_FLOW_CONTROL               (HAL_USART_FLOW_CONTROL_NONE)
// [USART2]$

// $[USART3]

// [USART3]$

// $[VCOM]
// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

// $[WTIMER1]
// [WTIMER1]$

#endif /* HAL_CONFIG_H */

